config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :customers do
    member do
      get :measurement_value
    end
  end
  resources :orders do
    member do
      patch :mark_complete
      patch :mark_delivered
      get :print
    end
  end
  resources :measurement_types do
    member do
      get :usage_info
    end
  end
  resources :tailors
  root 'dashboard#index'

  resource :profiles, only: [:show, :update] do
    patch :update_shop
    patch :update_tailor_limit
    delete :remove_logo
  end

  resources :subscriptions, only: [:show, :edit, :update] do
    member do
      patch :upgrade
      patch :downgrade
      patch :cancel
    end
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100 shadow-sm fixed top-0 z-30">
  <div class="navbar-start">
    <% if user_signed_in? %>
      <div class="">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle lg:hidden">
          <label for="my-drawer-2" class="drawer-button">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /> </svg>
          </label>
        </div>
      </div>
    <% end %>
  </div>
  <div class="navbar-center">
    <a href="/" class="btn btn-ghost text-xl"><%= t('app_name') %></a>
  </div>
  <div class="navbar-end">
    <!-- Language Switcher -->
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129" />
        </svg>
      </div>
      <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
        <%= link_to "English", { locale: :en }, class: "btn btn-ghost #{'btn-active' if I18n.locale == :en}" %>
        <%= link_to "اردو", { locale: :ur }, class: "btn btn-ghost #{'btn-active' if I18n.locale == :ur}" %>
      </ul>
    </div>

    <!-- Theme toggle button -->
    <button id="theme-toggle" class="btn btn-ghost btn-circle" data-action="click->theme#toggle">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 theme-light-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 theme-dark-icon hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
      </svg>
    </button>
    
    <% if user_signed_in? %>
      <!-- <button class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /> </svg>
      </button> -->
      
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <% if current_shop_logo&.attached? %>
              <%= image_tag current_shop_logo, class: "navbar-avatar" %>
            <% else %>
              <img alt="Avatar" src="https://ui-avatars.com/api/?name=<%= current_shop&.name&.first || 'S' %>&background=random" class="navbar-avatar" />
            <% end %>
          </div>
        </div>
        <ul tabindex="0" class="menu dropdown-content bg-base-200 rounded-box z-[1] mt-4 w-52 p-2 shadow-sm">
          <% if current_user.owner? %>
            <li>
              <%= link_to t('profile.title'), profiles_path, class: "justify-between" %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "justify-between", data: { turbo_method: :delete } do %>
              <%= t('actions.sign_out') %>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div> 

app/views/shared/_sidebar.html.erb
<div class="drawer-side shadow-sm">
  <label for="my-drawer-2" aria-label="close sidebar" class="drawer-overlay"></label>
  <ul class="menu bg-base-100 text-base-content w-64 p-4 h-full overflow-y-auto">
    <!-- Shop name/logo -->
    <li class="mb-4 shop-info">
      <div class="flex flex-col items-left py-4">
        <% if current_shop_logo&.attached? %>
          <%= image_tag current_shop_logo, class: "w-16 h-16 rounded-lg sidebar-logo mb-2" %>
        <% end %>
        <h2 class="text-lg font-semibold shop-name"><%= current_shop&.name %></h2>
      </div>
    </li>

    <!-- Sidebar content here -->
    <li class="mb-4">
      <%= link_to root_path, class: "#{current_page?(root_path) ? 'active' : ''}" do %>
        <%= image_tag "dashboard.png", class: "h-8 w-8" %>
        <%= t('navigation.dashboard') %>
      <% end %>
    </li>
    
    <% if current_user&.owner? %>
      <li class="mb-4">
        <%= link_to customers_path, class: "#{controller_name == 'customers' ? 'active' : ''}" do %>
          <%= image_tag "customers.png", class: "h-8 w-8" %>
          <%= t('navigation.customers') %>
        <% end %>
      </li>
    <% end %>
    
    <li class="mb-4">
      <%= link_to orders_path, class: "#{controller_name == 'orders' ? 'active' : ''}" do %>
        <%= image_tag "order-1.svg", class: "h-8 w-8" %>
        <%= t('navigation.orders') %>
      <% end %>
    </li>
    
    <% if current_user&.owner? %>
      <li class="mb-4">
        <%= link_to measurement_types_path, class: "#{controller_name == 'measurement_types' ? 'active' : ''}" do %>
          <%= image_tag "measurement.svg", class: "h-8 w-8" %>
          <%= t('navigation.measurement_types') %>
        <% end %>
      </li>
    <% end %>

    <% if current_user&.owner? %>
      <li class="mb-4">
        <%= link_to tailors_path, class: "#{controller_name == 'tailors' ? 'active' : ''}" do %>
          <%= image_tag "tailor.png", class: "h-8 w-8" %>
          <%= t('navigation.tailors') %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>